export const INCREMENT_SCORE = "INCREMENT_SCORE";
export const DECREMENT_SCORE = "DECREMENT_SCORE";
export const CHANGE_MAX_SCORE = "CHANGE_MAX_SCORE";

export const INCREMENT_NB_SHOOTS = "INCREMENT_NB_SHOOTS";
export const DECREMENT_NB_SHOOTS = "DECREMENT_NB_SHOOTS";
export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const RESET_SCORE = "RESET_SCORE";

export const SET_DATAS = "SET_DATAS";
export const FETCH_DATAS_FAIL = "FETCH_DATAS_FAIL";

// export const SEND_DATAS_START = "SEND_DATAS_START";
// export const SEND_DATAS_SUCCESS = "SEND_DATAS_SUCCESS";
export const SEND_DATAS_FAIL = "SEND_DATAS_FAIL";

export const CLEAN_DATAS = "CLEAN_DATAS";
